# .rubocop.yml
plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  
Style/Documentation:
  Enabled: false
